steps:
  - name: 'maven:3.8.6'
    entrypoint: 'mvn'
    args: ['clean', 'package']

  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'asia-southeast1-docker.pkg.dev/poetic-freedom-451723-b7/cloud-run-source-deploy/dolphin-admin-backend/dolphin-admin-backend',
      '.'
    ]

  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'asia-southeast1-docker.pkg.dev/poetic-freedom-451723-b7/cloud-run-source-deploy/dolphin-admin-backend/dolphin-admin-backend'
    ]

images:
  - 'asia-southeast1-docker.pkg.dev/poetic-freedom-451723-b7/cloud-run-source-deploy/dolphin-admin-backend/dolphin-admin-backend'
