#version: #tells Docker Compose which features are available.
#Version 3.8 is designed for Docker Engine 19.03+.

services:
  app:
    build: .
    image: dolphin-http:latest  # Using a consistent image name
    container_name: http8080
    # restart: always
    ports:  
      - "${APP_PORT:-8080}:8080"
    environment:
      - SOCKET_HOST=0.0.0.0
      - SOCKET_PORT=8080
      - JWT_SECRET=${JWT_SECRET}
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - TZ=Asia/Kuala_Lumpur

